#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediator
      group: core
      component: mediator
  template:
    metadata:
      labels:
        app: mediator
        group: core
        component: mediator
    spec:
      containers:
      - name: mediator
        envFrom:
          - configMapRef:
              name: mediator-env
          - secretRef:
              name: mediator-env-secret
        image: mediator:latest
        args: ["start"]
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
          - containerPort: 8082
            protocol: TCP
            name: ws-port
          - containerPort: 8083
            protocol: TCP
            name: api-port
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: api-port
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
