#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: edge-sandbox-

commonLabels:
  component: edv
  group: core
  instance: local
  project: trustbloc

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- path: edv/replacements.yml
  source: null
  targets: null
- path: oathkeeper/replacements.yml
  source: null
  targets: null
- source:
    kind: Secret
    name: edv-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: edv
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: edv-oathkeeper-proxy

replicas:
- count: 1
  name: edv

configMapGenerator:
- behavior: merge
  envs:
  - edv/config.env
  name: edv-env
- files:
  - certs/ca.crt
  name: edv-ca-cert

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: edv-wildcard-cert
  type: kubernetes.io/tls
- files:
  - ./keys/edv-gnap-key.pem
  name: edv-gnap-key

transformers:
- sedtransform.yml
- sedb64transform.yml

resources:
- ../common
- edv/ingress.yml
- oathkeeper/ingress.yml

patchesStrategicMerge:
- edv/add-ca.yml
- edv/add-key.yml
- oathkeeper/update-local-cert-store.yml
