#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediator
spec:
  template:
    spec:
      volumes:
        - name: ca-cert
          configMap:
            name: mediator-ca-cert
      containers:
        - name: mediator
          volumeMounts:
            - name: ca-cert
              mountPath: /etc/wallet/tls
