#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: svceng
kind: SedB64Transformer
metadata:
  name: sedb64transformer
argsOneLiner: s^||ARIESD_DATABASE_URL||^${ARIESD_DATABASE_URL}^ s^||MEDIATOR_DSN_PERSISTENT||^${MEDIATOR_DSN_PERSISTENT}^ s^||MEDIATOR_DSN_TRANSIENT||^${MEDIATOR_DSN_TRANSIENT}^
