#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: hub-auth
  group: core
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: hub-auth-wildcard-cert
  type: kubernetes.io/tls
- behavior: replace
  files:
  - ../keys/auth.key
  - ../keys/enc.key
  name: hub-auth-keys

configMapGenerator:
- behavior: merge
  envs:
  - auth.env
  name: hub-auth-env
- files:
  - ../certs/ca.crt
  name: hub-auth-ca-cert

replacements:
- path: replacements.yml
  source: null
  targets: null
- source:
    kind: Secret
    name: hub-auth-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: hub-hydra
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: hub-hydra-admin
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: hub-auth

resources:
- ../../common
- ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

patchesStrategicMerge:
- add-ca.yml
