# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: router
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: router
    group: core
    component: hub-router
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: router-ws
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: ws-port
  selector:
    app: router
    group: core
    component: hub-router
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: router-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: api-port
  selector:
    app: router
    group: core
    component: hub-router
status:
  loadBalancer: {}
