#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      group: wallet
  template:
    metadata:
      labels:
        app: web
        group: wallet
    spec:
      volumes:
        - name: nginx-config-template
          configMap:
            name: nginx-config-template
        - name: static-images
          configMap:
            name: static-images
        - name: static-icons
          configMap:
            name: static-icons
        - name: static-config
          configMap:
            name: static-config
        - name: static-manifest
          configMap:
            name: static-manifest
      containers:
      - name: web
        envFrom:
          - configMapRef:
              name: web-env
          - secretRef:
              name: web-env-secret
        image: wallet-web:latest
        ports:
          - containerPort: 80
            protocol: TCP
            name: http-port
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http-port
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        volumeMounts:
          - name: nginx-config-template
            mountPath: /etc/nginx/templates
            readOnly: true
          - name: static-images
            mountPath: /etc/static/images
            readOnly: true
          - name: static-icons
            mountPath: /etc/static/images/icons
            readOnly: true
          - name: static-config
            mountPath: /etc/static/config
            readOnly: true
          - name: static-manifest
            mountPath: /etc/static
            readOnly: true
