#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-router
spec:
  template:
    spec:
      volumes:
        - name: ca-cert
          configMap:
            name: router-ca-cert
      containers:
        - name: router
          volumeMounts:
            - name: ca-cert
              mountPath: /etc/wallet/tls
