#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: hub-router
  group: core
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: router-wildcard-cert
  type: kubernetes.io/tls

configMapGenerator:
- behavior: merge
  envs:
  - config.env
  name: router-env
- files:
  - certs/ca.crt
  name: router-ca-cert

replacements:
- path: router/replacements.yml
- path: router-api/replacements.yml
- path: router-ws/replacements.yml
- source:
    kind: Secret
    name: router-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: router
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: router-api
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: router-ws

resources:
- ../common
- router/ingress.yml
- router-api/ingress.yml
- router-ws/ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml

patchesStrategicMerge:
- add-ca.yml
