#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: resolver
  group: core
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

transformers:
- sedtransform.yml

#- ../../components/driver-did-sov
components:
- ../../components/uni-resolver-web

configMapGenerator:
- behavior: replace
  files:
  - resolver/config.json
  name: did-resolver-config
- behavior: merge
  envs:
  - resolver/config.env
  name: did-resolver-env
- behavior: replace
  files:
  - uni-resolver-web/config.json
  name: uni-resolver-web-config
