#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: auth
  group: services
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- path: hydra/replacements.yml
  source: null
  targets: null
- path: hydra-admin/replacements.yml
  source: null
  targets: null
- source:
    kind: Secret
    name: auth-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: auth-hydra
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: auth-hydra-admin

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: auth-wildcard-cert
  type: kubernetes.io/tls


configMapGenerator:
- files:
  - ../certs/ca.crt
  name: adapter-ca-cert

resources:
- ../../common
- hydra/ingress.yml
- hydra-admin/ingress.yml

transformers:
- sedtransform.yml
- sedb64transform.yml
