#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hydra
  newName: oryd/hydra
  newTag: v1.3.2-alpine

secretGenerator:
- envs:
  - hydra-secret.env
  name: hydra-secret

configMapGenerator:
- envs:
  - hydra-env.env
  name: hydra-env

resources:
- hydra.yml
