#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

configMapGenerator:
  - envs:
      - config.env
    name: trillian-log-signer-env

secretGenerator:
  - envs:
      - secret.env
    name: trillian-log-signer-env-secret

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: trillian-log-signer
  newName: ghcr.io/trustbloc-cicd/vct-log-signer
  newTag: v1.0.0-rc3-snapshot-7f594d9

resources:
- trillian-log-signer.yml
