#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

providers:
  mockbank:
    url: https://hydra.||DOMAIN||/
    clientID: auth
    clientSecret: auth-secret
    name: Demo OIDC
    signUpIconURL:
      en: https://auth.||DOMAIN||/static/images/en--demo-sign-up-button.svg
      fr: https://auth.||DOMAIN||/static/images/fr--demo-sign-up-button.svg
    signInIconURL:
      en: https://auth.||DOMAIN||/static/images/en--demo-sign-in-button.svg
      fr: https://auth.||DOMAIN||/static/images/fr--demo-sign-in-button.svg
    order: 1