#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.

commonLabels:
  component: auth
  group: core
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- behavior: merge
  envs:
  - auth-secret.env
  name: auth-env-secret

configMapGenerator:
- behavior: merge
  envs:
  - auth.env
  name: auth-env
- behavior: replace
  files:
  - providers.yml=auth-config.yml
  name: auth-config
- files:
    - ./static/images/en--demo-sign-in-button.svg
    - ./static/images/en--demo-sign-up-button.svg
  name: auth-static-images
- files:
    - ./static/config/access_policy.json
  name: auth-static-config

resources:
- ../../base

transformers:
- sedtransform.yml
- sedb64transform.yml
